---
elasticsearch:
  version: 7.5.0
  node:
    count: 3
    master: true
    data: true
    ingest: true
    allow_mmap: true
    java_opts: '-Xms2g -Xmx2g'
  storage:
    provisioner: 'kubernetes.io/gce-pd'
    enabled: true
    size: '10Gi'
    class:
      name: 'default'
      create: false
      parameters: #this will need to be customised for cloud providers other than gce
        type: gc-ssd
  service:
    type: 'LoadBalancer'
    sourceRange: {}
  snapshot:
    type: "false"
    destinatiom: false
    schedule: false
    credentialsSecret: "gcs-credentials"

tls:
  enabled: false
  secretName: ''

kibana:
  node:
    memory: 1Gi
    cpu: 1
    count: 2
