---
apiVersion: 'elasticsearch.k8s.elastic.co/v1'
kind: Elasticsearch
metadata:
  name: {{.Release.Name}}
  namespace: {{.Release.Namespace}}
spec:
  version: {{.Values.elasticsearch.version}}
  secureSettings:
  - secretName: {{ .Values.elasticsearch.snapshot.credentialsSecret }}
  nodeSets:
    - name: {{.Release.Name}}
      count: {{.Values.elasticsearch.node.count}}
      podTemplate:
        spec:
          initContainers:
          - command:
            - sh
            - -c
            - sysctl -w vm.max_map_count=262144
            name: set-max-map-count
            securityContext:
              privileged: true
          {{- if (eq .Values.elasticsearch.snapshot.type "gcs")}}
          - name: install-plugins
            command:
            - sh
            - -c
            - |
              bin/elasticsearch-plugin install --batch repository-gcs
          {{- end }}
          containers:
          - name: elasticsearch
            env:
            - name: ES_JAVA_OPTS
              value: "{{.Values.elasticsearch.node.java_opts}}"
            resources:
              requests:
                memory: 4Gi
      config:
        node.master: {{.Values.elasticsearch.node.master}}
        node.data: {{.Values.elasticsearch.node.data}}
        node.ingest: {{.Values.elasticsearch.node.ingest}}
        node.store.allow_mmap: {{.Values.elasticsearch.node.allow_mmap}}
      volumeClaimTemplates:
        - metadata:
            name: {{.Release.Name}}
            namespace: {{.Release.Namespace}}
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: {{.Values.elasticsearch.storage.size}}
            storageClassName: {{.Values.elasticsearch.storage.class.name}}
  http:
    service:
      spec:
        # expose this cluster Service with a LoadBalancer
        type: {{.Values.elasticsearch.service.type}}
    {{- if .Values.tls.enabled }}
    tls:
      certificate:
        # provide your own certificate
        secretName: {{.Values.tls.secretName}}
    {{- end }}
